name: tl_flutter_plugin
description: Acoustic Tealeaf can monitor traffic between your application and server. It captures device context and user activity to monitor and evaluate the performance of your applications
version: 2.0.21-beta
homepage: https://pub.dev/packages/tl_flutter_plugin
repository: https://github.com/acoustic-analytics/TL-Flutter-Plugin
build-name: 2.0.21-beta
build-number: 2.0.21-beta
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=2.5.0'
dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.1
  http: ^0.13.4
  logger: ^2.0.2+1
  yaml: ^3.1.1
  package_info: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  mockito: ^5.4.4
  path: ^1.8.3
flutter:
  plugin:
    platforms:
      android:
        package: com.example.tl_flutter_plugin
        pluginClass: TlFlutterPlugin
      ios:
        pluginClass: TlFlutterPlugin
  assets:
  - pubspec.yaml
false_secrets:
- /example/gallery/android/app/google-services.json
- /example/gallery/ios/Runner/GoogleService-Info.plist
- /example/gallery/lib/firebase_options.dart
- /example/gallery/macos/Runner/GoogleService-Info.plist
